### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by Rexathion1** [vapronva/nebula_tv_downloader-media_api#2]
@vapronva Thanks for the update ! it was exactly what i wanted , but unfortunately when i tried to use the tool i got the following error 

**When I set the AUTHORIZATION_HEADER**
```
2022-11-09 15:01:18,176 - DEBUG - Fetching auth user token is '7b1f...
2022-11-09 15:01:18,176 - DEBUG - Authorization header already set (`'eyJ0eXAiO...`), not fetching authorization token
2022-11-09 15:01:18,176 - DEBUG - Passed NebulaUserAuthorzation post initialization checks
2022-11-09 15:01:18,177 - DEBUG - Starting new HTTPS connection (1): content.api.nebula.app:443
2022-11-09 15:01:19,320 - DEBUG - https://content.api.nebula.app:443 "GET /video/?category=true HTTP/1.1" 403 35
Traceback (most recent call last):
  File "/home/ubuntu/nebula_tv_downloader-media_api/main.py", line 87, in <module>
    main()
  File "/home/ubuntu/nebula_tv_downloader-media_api/main.py", line 31, in main
    channels = get_all_channels_slugs_from_video_feed(
  File "/home/ubuntu/nebula_tv_downloader-media_api/NebulaAPI/VideoFeedFetcher.py", line 63, in get_all_channels_slugs_from_video_feed
    raise Exception(
Exception: Failed to get video feed: `b'{"detail":"Failed to decode to'...` with status code 403
```
**and when i use USER_API_TOKEN if fails to get auth token**
```
2022-11-09 20:42:42,213 - DEBUG - Fetching authorization token with user token '7b1f...
2022-11-09 20:42:42,214 - DEBUG - Starting new HTTPS connection (1): users.api.nebula.app:443
2022-11-09 20:42:45,803 - DEBUG - https://users.api.nebula.app:443 "POST /api/v1/authorization/ HTTP/1.1" 401 27
Traceback (most recent call last):
  File "/home/rd/nebula_tv_downloader-media_api/main.py", line 20, in <module>
    NEBULA_AUTH = NebulaUserAuthorzation(
  File "/home/rd/nebula_tv_downloader-media_api/NebulaAPI/Authorization.py", line 11, in __init__
    self.__fetch_authrizaton_token()
  File "/home/rd/nebula_tv_downloader-media_api/NebulaAPI/Authorization.py", line 37, in __fetch_authrizaton_token
    raise Exception(
Exception: Failed to get authorization token for a given user token: `b'{"detail":"Invalid token."}'` with status code 401
```

I checked if my auth header and user api token were actually valid by making a manual request using insomnia and it works when i do it manually . Anyways i am sure this is a minor bug or my own mistake , let me know what you think it could be . Again thanks for the update and the tool . Have a good day

**Comment by vapronva** [comment]
As far as I can see, you put some config variables in quotes (`'`). Seems like Python's [`ConfigParser`](https://docs.python.org/3/library/configparser.html) does not strip quotes from a given config variable, and I haven't even thought of that.

As of 383c9f27f2e0bfb7373dbe4a8211c8481d4572e6 quotes (`"` and `'`) are stripped from the variable before returning.

Works fine from my end, please let me know if everything's working now.

**Comment by Rexathion1** [comment]
ah i see , i was suspecting i might have done something like that :smile: , i have a habit of using quotes for strings . Thanks for letting me know and updating . it works perfectly now :+1:

**Comment by vapronva** [comment]
It's fine! I guess, it's a good habit 😄 \
Thanks for taking your time to report and write and the issue.

Anyways, will be closing the issue now.
