### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by thisguyshouldworkforus** [vapronva/nebula_tv_downloader-media_api#3]
What is the value of `AUTHORIZATION_HEADER = ` in the `config.ini` file supposed to be? The `README.md` does not mention it. When it is left blank, I get the error:

```bash
2024-03-13 08:46:29,157 - DEBUG - Fetching authorization token with user token `eyJhb...`
2024-03-13 08:46:29,158 - DEBUG - Starting new HTTPS connection (1): users.api.nebula.app:443
2024-03-13 08:46:29,457 - DEBUG - https://users.api.nebula.app:443 "POST /api/v1/authorization/ HTTP/1.1" 401 27
Traceback (most recent call last):
  File "/opt/projects/nebula_tv_downloader-media_api/main.py", line 20, in <module>
    NEBULA_AUTH = NebulaUserAuthorzation(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/projects/nebula_tv_downloader-media_api/NebulaAPI/Authorization.py", line 11, in __init__
    self.__fetch_authrizaton_token()
  File "/opt/projects/nebula_tv_downloader-media_api/NebulaAPI/Authorization.py", line 38, in __fetch_authrizaton_token
    raise Exception(
Exception: Failed to get authorization token for a given user token: `b'{"detail":"Invalid token."}'` with status code 401
```

When I put in the value from the Inspector (Inspect > Authorization > Request Headers > Authorization):
```bash
Token ae632f2eyrt651d5cd07f004e0d29ab238tha807a
```

I get an error:
```bash
2024-03-13 08:45:41,140 - DEBUG - Fetching authorization token with user token `eyJhb...`
2024-03-13 08:45:41,140 - DEBUG - Authorization header already set (`Token ae63...`), not fetching authorization token
2024-03-13 08:45:41,140 - DEBUG - Passed NebulaUserAuthorzation post initialization checks
2024-03-13 08:45:41,141 - DEBUG - Using channels from config: ['johnnyharris']
2024-03-13 08:45:41,141 - INFO - Fetching episodes for channel `johnnyharris`
2024-03-13 08:45:41,143 - DEBUG - Starting new HTTPS connection (1): content.api.nebula.app:443
2024-03-13 08:45:41,502 - DEBUG - https://content.api.nebula.app:443 "GET /video/channels/johnnyharris/ HTTP/1.1" 403 89
Traceback (most recent call last):
  File "/opt/projects/nebula_tv_downloader-media_api/main.py", line 87, in <module>
    main()
  File "/opt/projects/nebula_tv_downloader-media_api/main.py", line 38, in main
    channelData = get_channel_video_content(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/projects/nebula_tv_downloader-media_api/NebulaAPI/ChannelVideos.py", line 64, in get_channel_video_content
    raise Exception(
Exception: Failed to get channel video content for `johnnyharris`: `b'{"detail":"Authorization header expected to be of form: `Authorization: Bearer <token>`"}'` with status code 403
```

and when I omit the word `Token` from the string, I get the error:
```bash
2024-03-13 08:50:10,205 - DEBUG - Fetching authorization token with user token `eyJhb...`
2024-03-13 08:50:10,205 - DEBUG - Authorization header already set (`ae632f2e71...`), not fetching authorization token
2024-03-13 08:50:10,205 - DEBUG - Passed NebulaUserAuthorzation post initialization checks
2024-03-13 08:50:10,205 - DEBUG - Using channels from config: ['johnnyharris']
2024-03-13 08:50:10,205 - INFO - Fetching episodes for channel `johnnyharris`
2024-03-13 08:50:10,207 - DEBUG - Starting new HTTPS connection (1): content.api.nebula.app:443
2024-03-13 08:50:10,542 - DEBUG - https://content.api.nebula.app:443 "GET /video/channels/johnnyharris/ HTTP/1.1" 403 35
Traceback (most recent call last):
  File "/opt/projects/nebula_tv_downloader-media_api/main.py", line 87, in <module>
    main()
  File "/opt/projects/nebula_tv_downloader-media_api/main.py", line 38, in main
    channelData = get_channel_video_content(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/projects/nebula_tv_downloader-media_api/NebulaAPI/ChannelVideos.py", line 64, in get_channel_video_content
    raise Exception(
Exception: Failed to get channel video content for `johnnyharris`: `b'{"detail":"Failed to decode token"}'` with status code 403
```

I was able to successfully get the `USER_API_TOKEN = ` but I'm still missing this value.

**Comment by vapronva** [comment]
You got it right, but the **`AUTHORIZATION_HEADER` field must be empty**, and `USER_API_TOKEN` must be populated with the token value (just as you did in your last example):

```ini
[NebulaAPI]
USER_API_TOKEN = ae632f2eyrt651d5cd07f004e0d29ab238tha807a
AUTHORIZATION_HEADER =
```

Also, please pull a small change from cfaf6f3e44329da9ac9d179095338dcf8731b183 to update API models, otherwise the code will throw a few validation errors.

Let me know if it works!

// on a side note: thanks for creating this issue!
// honestly, it's been more than a year since i last touched this project, and am surprised it still works. will look into rewriting or at least making the docs better.

**Comment by thisguyshouldworkforus** [comment]
I re-cloned and checked out your mentioned commit. Its running great.

**Comment by vapronva** [comment]
Great! I will be closing the issue then. Don't hesitate to reach out if any other questions arise.
